services:
  NG_API:
    container_name: NG_API
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - psql_db
    command: bash -c "yarn prisma migrate dev && yarn dev"
  psql_db:
    container_name: postgres_database
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432